"use client";

import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { z } from "zod";
import { AlertCircle, BadgePercent, Loader2, Pencil, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/context/auth-context";
import { api } from "@/services/api";
import type { Promocion } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { EmptyState } from "@/components/shared/EmptyState";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";

const schema = z.object({ codigo: z.string().trim().min(1, "El código es obligatorio"), descripcion: z.string().optional(), porcDesc: z.coerce.number().gt(0, "Debe ser mayor que 0").lte(100, "No puede superar el 100%"), activa: z.boolean(), fechaInicio: z.string().min(1, "Indicá el inicio"), fechaFin: z.string().min(1, "Indicá el fin") }).refine((data) => new Date(data.fechaFin) > new Date(data.fechaInicio), { path: ["fechaFin"], message: "La fecha de fin debe ser posterior al inicio" });
type FormData = z.infer<typeof schema>;
const emptyForm: FormData = { codigo: "", descripcion: "", porcDesc: 10, activa: true, fechaInicio: new Date().toISOString().slice(0, 16), fechaFin: new Date(Date.now() + 86400000).toISOString().slice(0, 16) };
const fallbackEndDate = "2999-01-01T00:00:00.000Z";

function status(p: Promocion) { const now = Date.now(); const start = p.fechaInicio ? new Date(p.fechaInicio).getTime() : 0; const end = p.fechaFin ? new Date(p.fechaFin).getTime() : Infinity; return !p.activa ? "Desactivada" : now < start ? "Programada" : now > end ? "Finalizada" : "Activa"; }

export default function AdminPromocionesPage() {
  const qc = useQueryClient();
  const [editing, setEditing] = useState<Promocion | null>(null);
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState<FormData>(emptyForm);
  const [errors, setErrors] = useState<Partial<Record<keyof FormData, string>>>({});
  const { isReady, isAuthenticated } = useAuth();
  const { data: promociones = [], isLoading, error } = useQuery({ queryKey: ["admin-promociones"], queryFn: api.admin.promociones.listar, enabled: isReady && isAuthenticated });
  const mutation = useMutation({ mutationFn: (data: FormData) => { const payload = { ...data, fechaInicio: new Date(data.fechaInicio).toISOString(), fechaFin: new Date(data.fechaFin).toISOString() }; return editing ? api.admin.promociones.actualizar(editing.idPromocion, payload) : api.admin.promociones.crear(payload); }, onSuccess: () => { qc.invalidateQueries({ queryKey: ["admin-promociones"] }); qc.invalidateQueries({ queryKey: ["promociones"] }); setOpen(false); toast.success(editing ? "Promoción actualizada" : "Promoción creada"); }, onError: (err) => toast.error(err instanceof Error ? err.message : "No se pudo guardar la promoción") });
  const deleteMutation = useMutation({ mutationFn: api.admin.promociones.eliminar, onSuccess: () => { qc.invalidateQueries({ queryKey: ["admin-promociones"] }); qc.invalidateQueries({ queryKey: ["promociones"] }); toast.success("Promoción desactivada"); }, onError: (err) => toast.error(err instanceof Error ? err.message : "No se pudo desactivar") });
  const sorted = useMemo(() => [...promociones].sort((a, b) => status(a).localeCompare(status(b))), [promociones]);
  const openNew = () => { setEditing(null); setForm(emptyForm); setErrors({}); setOpen(true); };
  const openEdit = (p: Promocion) => { setEditing(p); setForm({ codigo: p.codigo, descripcion: p.descripcion ?? "", porcDesc: Number(p.porcDesc), activa: p.activa, fechaInicio: (p.fechaInicio ?? p.createdAt).slice(0, 16), fechaFin: (p.fechaFin ?? fallbackEndDate).slice(0, 16) }); setErrors({}); setOpen(true); };
  const submit = () => { const result = schema.safeParse(form); if (!result.success) { setErrors(Object.fromEntries(result.error.issues.map((issue) => [issue.path[0], issue.message]))); return; } setErrors({}); mutation.mutate(result.data); };

  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-display text-xl font-semibold">Promociones</h2><p className="text-sm text-muted-foreground">Códigos porcentuales y su vigencia.</p></div><Button onClick={openNew} className="rounded-full"><Plus className="size-4" /> Nueva promoción</Button></div><div className="rounded-2xl border border-border bg-card shadow-soft">{isLoading ? <div className="space-y-4 p-6">{Array.from({ length: 4 }).map((_, i) => <Skeleton key={i} className="h-10 w-full" />)}</div> : error ? <div className="py-12"><EmptyState icon={AlertCircle} title="Error al cargar promociones" description={error.message} /></div> : sorted.length === 0 ? <div className="py-12"><EmptyState icon={BadgePercent} title="Sin promociones" description="Creá el primer código promocional." /></div> : <div className="divide-y divide-border">{sorted.map((p) => <div key={p.idPromocion} className="flex flex-wrap items-center justify-between gap-4 p-4"><div><div className="flex items-center gap-2"><strong>{p.codigo}</strong><Badge variant={status(p) === "Activa" ? "secondary" : "outline"}>{status(p)}</Badge></div><p className="text-sm text-muted-foreground">{p.descripcion || "Sin descripción"} · {p.porcDesc}%</p><p className="text-xs text-muted-foreground">Inicio: {p.fechaInicio ? new Date(p.fechaInicio).toLocaleString("es-AR") : "No informado"} · Fin: {p.fechaFin ? new Date(p.fechaFin).toLocaleString("es-AR") : "No informado"}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" className="rounded-full" onClick={() => openEdit(p)}><Pencil className="size-3.5" /> Editar</Button><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" size="icon" className="rounded-full text-destructive"><Trash2 className="size-4" /></Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Desactivar promoción</AlertDialogTitle><AlertDialogDescription>El código dejará de estar disponible para nuevas compras.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={() => deleteMutation.mutate(p.idPromocion)}>Desactivar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></div>)}</div>}</div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? "Editar promoción" : "Nueva promoción"}</DialogTitle><DialogDescription>Usá un porcentaje entre 1 y 100 y definí su vigencia.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label htmlFor="promo-codigo">Código</Label><Input id="promo-codigo" value={form.codigo} onChange={(e) => setForm({ ...form, codigo: e.target.value.toUpperCase() })} />{errors.codigo && <p className="text-xs text-destructive">{errors.codigo}</p>}</div><div><Label htmlFor="promo-desc">Descripción</Label><Input id="promo-desc" value={form.descripcion} onChange={(e) => setForm({ ...form, descripcion: e.target.value })} /></div><div><Label htmlFor="promo-percent">Descuento (%)</Label><Input id="promo-percent" type="number" min="1" max="100" value={form.porcDesc} onChange={(e) => setForm({ ...form, porcDesc: Number(e.target.value) })} />{errors.porcDesc && <p className="text-xs text-destructive">{errors.porcDesc}</p>}</div><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="promo-start">Inicio</Label><Input id="promo-start" type="datetime-local" value={form.fechaInicio} onChange={(e) => setForm({ ...form, fechaInicio: e.target.value })} />{errors.fechaInicio && <p className="text-xs text-destructive">{errors.fechaInicio}</p>}</div><div><Label htmlFor="promo-end">Fin</Label><Input id="promo-end" type="datetime-local" value={form.fechaFin} onChange={(e) => setForm({ ...form, fechaFin: e.target.value })} />{errors.fechaFin && <p className="text-xs text-destructive">{errors.fechaFin}</p>}</div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.activa} onChange={(e) => setForm({ ...form, activa: e.target.checked })} /> Activa</label></div><DialogFooter><Button onClick={submit} disabled={mutation.isPending} className="rounded-full">{mutation.isPending && <Loader2 className="size-4 animate-spin" />} Guardar promoción</Button></DialogFooter></DialogContent></Dialog></div>;
}
